### ISSUE TITLE
When used under Windows with OpenRefine 3.6.1 the service fails - The endpoint MUST return a JSON document describing the service, accessible vîa CORS or JSONP.

### ISSUE THREAD

**Issue by MatsBjerin** [gitonthescene/csv-reconcile#83]
When used under Windows with OpenRefine 3.6.1 the service fails.
If I try using the OpenRefine Test Bench tab I get the following error: "The endpoint MUST return a JSON document describing the service, accessible vîa CORS or JSONP."

The output from the service from the test is:
 ```
* Serving Flask app 'csv-reconcile' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Sep/2022 21:57:05] "OPTIONS / HTTP/1.1" 404 -
127.0.0.1 - - [07/Sep/2022 21:57:05] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [07/Sep/2022 21:57:05] "OPTIONS /?callback=jsonp_1662580625915_97939 HTTP/1.1" 404 -
127.0.0.1 - - [07/Sep/2022 21:57:05] "GET /?callback=jsonp_1662580625915_97939 HTTP/1.1" 404 -
```

Might the OpenRefine protocol have changed?

**Comment by gitonthescene** [comment]
It’s possible.  I’ll have a look.  Thanks for the heads up.

**Comment by gitonthescene** [comment]
I just fired up OpenRefine 3.6.1 and initialized and ran csv-reconcile with the example from the README and it worked just fine.  You mentioned it failed when you used it under Windows but not the specific error you saw there.  I don't have access to Windows, but I'm happy to walk you through some troubleshooting.

I'm guessing the issue with the test bench is slightly different.  CORS is about secure communication over the web and you're running the service with http:// and not https://.  Setting up a service using https:// is a whole other matter that can be avoided if you run both the csv-reconcile service and OpenRefine on the same machine.  Since it's all local you would sidestep all the issues about secure communication.

I'll leave this issue open for a few days to wait to hear back about the specific problems you were having on Windows.  You can always open up a new issue with more detail about those issues if they're not resolved.

**Comment by MatsBjerin** [comment]
Thanks!
I did run both locally so https should not have been a factor.
But there can of course be issues with how I installed the module as well as the version of Python.

The error I get if I do not use the test bench is:
"Error contacting recon service: error : error - http://127.0.0.1:5000/"

The output from csv_reconcile is shown as:
127.0.0.1 - - [08/Sep/2022 18:53:26] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [08/Sep/2022 18:53:26] "GET /?callback=jQuery360020555374958264605_1662655812878&_=1662655812882 HTTP/1.1" 404 -

I.e. a page not found error.
Could it be an issue with file paths as Windows uses backslash?

**Comment by gitonthescene** [comment]
Ah, I think I know the problem.  The service (by default) is at the end point `http:/127.0.0.1:5000/reconcile` and _not_ `http:/127.0.0.1:5000` even though the latter is output when flask starts.  Try adding `/reconcile` as above.

You can turn on more logging by supplying a config file with `--config` and adding `LOGLEVEL="DEBUG"` to that file.

Please let me know if this advice works for you.

**Comment by MatsBjerin** [comment]
Excellent! With the correct URL it worked perfectly.
Thank you for helping me find the solution. It is really a very useful service you have built! :-)
Much appreciated! /Mats
