### ISSUE TITLE
Where do I put the .csv file I want to reconcile with the .csv file I upload to openRefine?

### ISSUE THREAD

**Issue by dorisavedikian** [gitonthescene/csv-reconcile#92]
I want to reconcile two csv's...Ive installed csv-reconcile and initialized the database....and Ive uploaded one of the csv's to openRefine....but I am not sure where to put the other file Im trying to reconcile it to....any help would be greatly appreciated. Thanks!!!

**Comment by gitonthescene** [comment]
So you’re reconciling one csv file _against_ another.  The one that you’re using as the base, i.e. the one you’re considering to have the information you’re looking for is used when you [initialize csv-reconcile](https://github.com/gitonthescene/csv-reconcile#quick-start).  In the sample given in the README it’s `sample/reps.tsv` but you should use yours with your id column and the column you’re using to reconcile.

In OpenRefine you load up the csv file you want to compare against the base csv.

So if you initialized csv-reconcile with the file you want you should be good to go.  If that doesn’t work can you please post the command you ran to initialize the database as well as any output you saw when running it?

If you’re good to go could you let me know?  Otherwise I’ll close this in a week.

**Comment by dorisavedikian** [comment]
Thanks for your reply. 

This is the command I am trying...

`csv-reconcile init reconciliation/nalt_labels_nodups.tsv Label NALT_URI`

Below is the error I am getting.  
![Screen Shot 2023-01-31 at 2 41 19 PM](https://user-images.githubusercontent.com/109038399/215900373-6304dda2-741d-408b-8daa-f4d7a17ced1d.png)

**Comment by gitonthescene** [comment]
Okay, I think I see the error.  See that last line where it says `UNIQUE constraint failed: reconcile.id`?  That’s saying that the column you gave for the ids doesn’t contain unique values.  I.e. there are two rows in your csv with the same id.

The image you posted is truncated at the top so I can’t see the exact name you used for the id column but it should be the first arg after the csv name.  Hopefully this is enough info to go on.  If not, please be sure to post the entire image.

**Comment by dorisavedikian** [comment]
As said, the file doesn't have any duplicates because I removed them....but, I changed the command I used based on your comment and it worked - I was able to do the reconciliation!! 

`csv-reconcile init reconciliationdata/nalt_labels_nodups.tsv NALT_URI Label`

Thanks a lot!!

**Comment by gitonthescene** [comment]
Awesome!  Congratulations.  Closing
